# -*- coding: utf-8 -*-
"""AI-Powered Voice Note Organizer: Organize Your Thoughts Effortlessly.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177RiW52UH_yWYAFMz9bNJbGcUoqUrATs
"""

!pip install openai-whisper transformers torch gradio datasets

import whisper
import torch
import gradio as gr
from transformers import pipeline

# Load Whisper model for speech-to-text
model = whisper.load_model("base")

# Load a BERT-based model for text classification

classifier = pipeline("zero-shot-classification", model="valhalla/distilbart-mnli-12-3")

def transcribe_and_classify(audio_file):
    # Transcribe the voice note
    result = model.transcribe(audio_file)
    text = result["text"]

    # Define classification categories
    categories = ["Tasks", "Ideas", "Meetings", "Reminders", "Notes"]

    # Classify the transcribed text into one of the categories
    classification = classifier(text, candidate_labels=categories)

    # Get the highest probability category
    top_category = classification["labels"][0]
    confidence = classification["scores"][0]

    return text, top_category, confidence

demo = gr.Interface(
    fn=transcribe_and_classify,
    inputs=gr.Audio(type="filepath"),  # FIXED LINE
    outputs=["text", "text", "number"],
    title="AI-Powered Voice Note Organizer",
    description="Upload a voice note to transcribe and categorize it into Tasks, Ideas, Meetings, Reminders, or Notes."
)

# Launch the UI
demo.launch()